### ISSUE TITLE
Allow for sorting by column

### ISSUE THREAD

**Issue by mr-zwets** [Panmoni/tokenstork#3]
A very cool feature would be that the different info categories in the first table row are clickable and that this way the table can be ordered (alphabetically, by marketcap, by TVL, by circulating supply etc.)

**Comment by georgedonnelly** [comment]
Excellent idea. I definitely want to add this ASAP. Thank you.

**Comment by georgedonnelly** [comment]
Sorting by price and TVL are enabled in version 0.0.2 on branch 002 and visible here: https://tokenstork-git-002-panmoni.vercel.app/.

The token list is default sorted by TVL on load, from higher TVL to lower TVL.

How important to you is the ability to sort the other number columns?

**Comment by mr-zwets** [comment]
nice work on the sorting! I think having sorting on both TLV and marketcap is valuable as market-cap based ordering has become the industry default .

**Comment by georgedonnelly** [comment]
That's a good point. I will move up the marketcap sorting. Thank you.

**Comment by georgedonnelly** [comment]
Marketcap sorting is now enabled on version 0.0.2 and is now live. Thanks for this issue. Please feel free to file more issues in the future. Closing.
