### ISSUE TITLE
Burned tokens not removed from circulating supply

### ISSUE THREAD

**Issue by dagurval** [Panmoni/tokenstork#5]
Burned tokens are not removed from circulating supply. 

For example, each interaction with the contract at [this address](https://explorer.bitcoinunlimited.info/address/bitcoincash:pd23d53rcs7c8gw4zq04wmn74a4a3xpwumhzhs83u4vl2qsswf6050z9dnv6p) burns one SOCK token

**Comment by georgedonnelly** [comment]
Thanks for this report. I will get this into the next release.

**Comment by georgedonnelly** [comment]
I'm working on a chaingraph query for this. Thanks for your patience.

**Comment by lovetillion** [comment]
This contract is very interesting...

How about for the original 149 SOCK burns https://x.com/CauldronSwap/status/1708470495501324702

And what would be a standard way to burn CashTokens so it could be done in a query unless we had a standard address (XLV needs to burn 20920999.420038) similar to ETH 0x0000000000000000000000000000000000000000

**Comment by georgedonnelly** [comment]
Maybe ask in https://t.me/cashtoken_devs

**Comment by georgedonnelly** [comment]
Thank you @lovetillion for the solution in PR9. https://github.com/Panmoni/tokenstork/pull/9

**Comment by georgedonnelly** [comment]
Closing.
